[package]
name = "tmzgua"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.69"
chrono = "0.4.26"
endorphin = "0.1.9"
regex = "1.9.1"
serde = { version = "1.0.166", features = ["derive"] }
serde_json = "1.0.99"
serenity = { version = "0.11", features = ["voice"] }
songbird = { version = "0.3", features = ["tokio", "serenity"]}
tap = "1.0.1"
tokio = { version = "1.29", features = ["macros", "rt-multi-thread", "process"] }
